### ISSUE TITLE
Online version, handling

### ISSUE THREAD

**Issue by LeonaMorro** [Sei-Lisa/LSL-PyOptimizer#10]
Hi Sei Lisa,
for me (windows/firefox) it would be nice if the Optimizer output would be placed inside a textarea or to have an option to get the raw optimizer output. With both variants I would be able to mark the complete output (windows: ctrl+A) and copy it to the clipboard. With the current version I have to mark the optimizer output manually (a little boring with larger scripts).

Greetings
Leona

**Comment by Sei-Lisa** [comment]
There is a link "[Select All]" at the top, which appears if you have JavaScript active.

**Comment by LeonaMorro** [comment]
Sorry, my fault (I usually have Java script disabled)

**Comment by Sei-Lisa** [comment]
I have made it more obvious for those who don't have JS active. Thanks for the report.
