### ISSUE TITLE
Combined lists getting incorrectly spliced

### ISSUE THREAD

**Issue by Tonaie** [Sei-Lisa/LSL-PyOptimizer#13]
For some reason I have only been able to reproduce it in this particular script:
[https://pastebin.com/2NR7Dgam](https://pastebin.com/2NR7Dgam)

Line 153: `runMethod((string)LINK_ROOT, "got Status", 1, (list)("")+ ((list)1 + 3 + (integer)(-cost*100) +  "" +  0), JSON_INVALID);`

When optimized becomes: `D("1", "got Status", 1, (list)1 + 3 + (integer)(-loc_cost * 100) + "" + 0, "﷐");`

As you can see it starts with `(list)1+3...` when it should be `(list)"" + 1 +3...`

**Comment by Sei-Lisa** [comment]
Indeed, thanks for the report! The problem involves adding the constant `""` and a non-constant list. Here's a simplified test case, which uses a function that produces a non-constant list (`llGetPhysicsMaterial`), and another function that causes side effects (`llParticleSystem`) and therefore prevents the list from being removed:

```lsl
default
{
    state_entry()
    {
        llParticleSystem("" + llGetPhysicsMaterial());
    }
}
```

This gets erroneously simplified to:

```lsl
default
{
    state_entry()
    {
        llParticleSystem(llGetPhysicsMaterial());
    }
}
```

I'm working on the fix.

**Comment by Sei-Lisa** [comment]
Fixed, thanks again!
