### ISSUE TITLE
Some float<->string conversions return incorrect results or raise an exception

### ISSUE THREAD

**Issue by SaladDais** [Sei-Lisa/LSL-PyOptimizer#17]
First of all, thank you for LSL-PyOptimizer, it's clearly been thoughtfully designed and written!

I'm putting these as one issue since they're all relatively small and are closely related, but let me know if you'd prefer I split them up. For reference, they're all based on assertions from LL's [LSL Language Test 2](https://wiki.secondlife.com/wiki/LSL_Language_Test_2).

----

`llOwnerSay((string)((float)"-0.0"));` is optimized to `llOwnerSay("0.000000");`, but SL outputs `-0.000000`.

I think the sign bit is lost due to the denormal handling at <https://github.com/Sei-Lisa/LSL-PyOptimizer/blob/c29475d0726384aada407b2a169c5cc1f732a663/lslopt/lslbasefuncs.py#L508>, and a `math.copysign()` may be needed if rounding to `0.0` is correct there.

----

`llOwnerSay((string)(1.4e-45 == (float)"1.4e-45"));` is optimized to `llOwnerSay("0");`, but SL outputs `1`. I think this is also related to the above handling of denormals in `string->float` conversions, but I'm not sure what the correct fix would be.

----

`llOwnerSay((string)0.00000000000001);` fails to compile and an `IndexError` is raised at <https://github.com/Sei-Lisa/LSL-PyOptimizer/blob/c29475d0726384aada407b2a169c5cc1f732a663/lslopt/lslbasefuncs.py#L391>

It looks like this may be an issue with any float small enough that the string representation is `0.000[...]`, but is not actually equal to `0.0`.

**Comment by Sei-Lisa** [comment]
Awesome tests, thanks a lot for the report!

`(string)0.00000000000001` was a screwup on my side, as the code wrongly assumed that there would be a nonzero digit in the first 13 decimals. Your test case places it in the 14th. Good catch.

The others are a change of behaviour. For a long time there has been a difference between LSO and Mono, causing strings that represented a denormal to be converted to zero when cast to float. This deviation was initially described by Pedro Oval in the wiki: https://wiki.secondlife.com/wiki/User_talk:Strife_Onizuka/Float_Functions#Bug_in_iuf and upon verification I committed a fix: https://github.com/Sei-Lisa/LSL-PyOptimizer/commit/aee638e900531ec51d5166561361be01eef77adc

I'm thankful that this is now fixed for good and denormals are now respected.

It's not the only change to the string to float cast. `(float)"-nan"` used to produce positive NaN; now it produces negative NaN, which is great.

It's all fixed now, see last commits. The string to float cast changes have caused several of the tests in the test suite to become invalid, so I've corrected them to account for the new behaviour. If there's anything I've missed please feel free to reopen.

I've included your test cases in the test suite, hope you don't mind.

**Comment by Sei-Lisa** [comment]
There's been another change. The original https://wiki.secondlife.com/wiki/LSL_Language_Test_2 is now failing one test, but the optimized version is passing it. The failed test is due to a change in the treatment of signed zero in `llDumpList2String`, which is now different to the behaviour you get when e.g. casting a list to string. I'm looking into it, but it looks like this one is going to be troublesome.

**Comment by SaladDais** [comment]
Thanks, everything looks great!

I wasn't aware of the `llDumpList2String()` failure case, I only dug into cases that failed LL's test suite's assertions. LSO and Mono give different results too, which I wouldn't have expected. Very odd.

**Comment by Sei-Lisa** [comment]
Fixed now to accommodate for the new behaviour. Now both the unoptimized and the optimized versions fail in the same way. Also, the conversion from float to string was rounding  improperly in some corner cases; hopefully that's now definitively fixed.

**Comment by Sei-Lisa** [comment]
Forgot to say, thanks again for pointing me to the tests and posting this report!
