### ISSUE TITLE
`integer global=other_global;` raises KeyError when ConstFold is disabled

### ISSUE THREAD

**Issue by SaladDais** [Sei-Lisa/LSL-PyOptimizer#19]
Sometimes I disable `ConstFold` to maintain readability of `if` / `else` chains, but it appears that causes issues when you have an `SAIdentifier` on the RHS of a global's declaration.

Given the script

```lsl
integer FOO=1;
integer BAR=FOO;
default {
  state_entry() {
    llOwnerSay((string)BAR);
  }
}
```

A `llOwnerSay("1");` will be correctly emitted when `ConstFold` is enabled, but when it's disabled an exception is raised:

```
Traceback (most recent call last):
  File "/home/user/source/LSL-PyOptimizer/main.py", line 779, in <module>
    ret = main(sys.argv)
  File "/home/user/source/LSL-PyOptimizer/main.py", line 742, in main
    script = script_header + script_timestamp + outs.output(ts, options)
  File "/home/user/source/LSL-PyOptimizer/lslopt/lsloutput.py", line 556, in output
    ret += self.OutCode(node)
  File "/home/user/source/LSL-PyOptimizer/lslopt/lsloutput.py", line 483, in OutCode
    ret += ' = ' + self.OutExpr(child[0])
  File "/home/user/source/LSL-PyOptimizer/lslopt/lsloutput.py", line 305, in OutExpr
    return self.FindName(expr)
  File "/home/user/source/LSL-PyOptimizer/lslopt/lsloutput.py", line 186, in FindName
    and 'NewName' in self.symtab[node.scope][node.name]):
KeyError: 'FOO'
```

Seems like `FOO` isn't in the symbol table for its scope at the point the RHS of `BAR`'s declaration is being handled?

**Comment by Sei-Lisa** [comment]
Ugh, that's one of the pitfalls in the dead code removal algorithm, which is far from perfect. I'll take a look, thanks a lot for the report! In the meantime you can disable DCR as well to work around the issue: `-O -constfold,-DCR`.

The 'if' swapping may be a bit too visually invasive indeed. Maybe I should provide a separate option to disable it.

**Comment by SaladDais** [comment]
> In the meantime you can disable DCR as well to work around the issue: `-O -constfold,-DCR`

Thanks, that works!

> The 'if' swapping may be a bit too visually invasive indeed. Maybe I should provide a separate option to disable it.

That would be very helpful. I like the XOR branching strategy, and I think it's a good default, but sometimes it hurts my brain to trace through and relate back to the original source during debugging

**Comment by Sei-Lisa** [comment]
Okay, I think I've put that one to rest, thanks for the report!

The option to disable the if/else swapping is out of scope for this issue, but I'll let you know here when it's implemented nevertheless. Meanwhile, if you could please check if this problem is solved in your real use case, with DCR enabled and constant folding disabled, that'd be appreciated.

**Comment by SaladDais** [comment]
Both `-ConstFold,+DCR` and the new `-IfElseSwap` behave as expected on `master`, thank you very much!
