### ISSUE TITLE
New LSL commands missing

### ISSUE THREAD

**Issue by PeterStindberg** [Sei-Lisa/LSL-PyOptimizer#27]
Hi there, there's a few new LSL functions that are missing: 
llLinksetDataDeleteFound
llLinksetDataCountFound

**Comment by Sei-Lisa** [comment]
This is not the place for this kind of requests. Please report missing functions, constants or events against the https://github.com/Sei-Lisa/kwdb repository, from which this repository takes its data. Thanks.

**Comment by Sei-Lisa** [comment]
FYI this is now updated together with more changes.
