### ISSUE TITLE
Update needed for PBR and other 2023 LSL Additions.

### ISSUE THREAD

**Issue by Kristyku** [Sei-Lisa/LSL-PyOptimizer#28]
An update is needed to support PBR values such as for set prim params:
PRIM_RENDER_MATERIAL https://wiki.secondlife.com/wiki/PRIM_RENDER_MATERIAL
PRIM_GLTF_BASE_COLOR https://wiki.secondlife.com/wiki/PRIM_GLTF_BASE_COLOR
PRIM_GLTF_NORMAL https://wiki.secondlife.com/wiki/PRIM_GLTF_NORMAL
PRIM_GLTF_METALLIC_ROUGHNESS https://wiki.secondlife.com/wiki/PRIM_GLTF_METALLIC_ROUGHNESS
PRIM_GLTF_EMISSIVE https://wiki.secondlife.com/wiki/PRIM_GLTF_EMISSIVE

As well as:

New function llGetInventoryDesc - returns the description of the inventory item: https://wiki.secondlife.com/wiki/LlGetInventoryDesc
New function llIsFriend - returns TRUE if agent_id and the owner of the prim the script is in are friends: https://wiki.secondlife.com/wiki/LlIsFriend
New function llRezObjectWithParams - apply a list of prim properties that are applied when the object is rezzed: https://wiki.secondlife.com/wiki/LlRezObjectWithParams
New function llListFindListNext - find the index of non-unique list entries beyond the first instance: https://wiki.secondlife.com/wiki/LlListFindListNext
llSetDamage can now set negative damage: https://wiki.secondlife.com/wiki/LlSetDamage

New LSL changed() event type https://wiki.secondlife.com/wiki/CHANGED_RENDER_MATERIAL

And maybe some others that I've missed.

**Comment by Sei-Lisa** [comment]
Please report this against [kwdb](https://github.com/Sei-Lisa/kwdb) next time, please.

The constants you mention are all implemented now, but none of the functions work for me. Does one need a certain channel to run these? As in LeTigre/BlueSteel/Magnum...

**Comment by Kristyku** [comment]
PBR functionality works grid-wide.

Others are part of 2023-11-20.6935786551 I'm not sure which channels it has been deployed in so far, but it might be deployed wider with today's/tomorrow's restarts.
Here's the release notes https://releasenotes.secondlife.com/simulator/2023-11-20.6935786551.html

I've heard that LL are trying to roll out that update grid-wide by the end of the year.

The latest changes are on Second Life Preflight 2023-11-20.6935786551 - which is available in Rumpus Room regions.

**Comment by Kristyku** [comment]
It would appear it has been rolled out on all RC Channels:
Second Life RC BlueSteel 2023-12-06.7120498618
Second Life RC Magnum 2023-12-06.7120498618
Second Life RC LeTigre 2023-12-06.7120498618

**Comment by Kristyku** [comment]
According to https://modemworld.me/2024/01/16/2024-sl-sug-meetings-week-3-summary/ the RC Sims are updating to also include another function: https://wiki.secondlife.com/wiki/LlGetNotecardLineSync

**Comment by PeterStindberg** [comment]
The functions have been rolled out gridwide on Tuesday. https://releasenotes.secondlife.com/simulator/2024-01-19.7590161929.html

**Comment by Sei-Lisa** [comment]
Almost 3 months later (sigh), kwdb has been updated with the latest keywords, and the changes imported. New functions implemented for constant value resolution (they work on [lslcalc](http://lsl.blacktulip-virtual.com/lslcalc/lslcalc.php) too):

- `llList2ListSlice`
- `llListFindListNext`
- `llListFindStrided`
- `llListSortStrided`
