### ISSUE TITLE
Mangles Unicode Literals

### ISSUE THREAD

**Issue by EricBLivingston** [Sei-Lisa/LSL-PyOptimizer#7]
This is likely a Python 2.7 thing, but this optimizer transforms something like this:

["⑬","①","⑲","⑨","⑩"]

Into this:

[ "Γæ¼", "Γæá", "Γæ▓", "Γæ¿", "Γæ⌐"]

Making this tool unfortunately unusable if any Unicode characters are present at all, it seems.

**Comment by EricBLivingston** [comment]
Wait a minute - I think that was the result of piping I was doing. I believe the output is ok if I put it directly into a "> output.lsl" file

**Comment by Sei-Lisa** [comment]
It's working fine for me, and it's working fine on the online version http://lsl.blacktulip-virtual.com/lsl-pyoptimizer/online.php? therefore this looks like an OS-specific problem.

What's your OS?

**Comment by EricBLivingston** [comment]
Windows 10 - what I was doing was grabbing the output of the optimizer in a console inside Notepad++ (using the NppExec addin) and then loading that directly into a new window. The issue seems to be that console. If I pipe the optimizer's output to an intermediate file and then load that (bypassing that console) then it seems to do fine. Sorry for raising an Issue here!

**Comment by Sei-Lisa** [comment]
Maybe using `chcp 65001` on the console before running the optimizer helps.

Remember also you have the `-o` option to write to a file directly, which bypasses piping.

This seems to come from Code Page 861. `⑩` is encoded as `0xE2 0x91 0xA9` in UTF-8, and in code page 861 code `E2` corresponds to `Γ`, `91` to `æ` and `A9` to `⌐`. Therefore changing the code page to Unicode (65001) might indeed help.

If that helps, see also https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8 to make it default.

**Comment by EricBLivingston** [comment]
Actually, as it happens I found an option with the NppExec plugin that changes the coding of its console to UTF-8, so I'm good to go! However, I may use your -o option anyway as it would be faster than the scrolling console window I'm outputting to. I'll give that a try
