### ISSUE TITLE
MemoryError in online version

### ISSUE THREAD

**Issue by LeonaMorro** [Sei-Lisa/LSL-PyOptimizer#9]
Hi Sei Lisa,
I tried the online version [http://lsl.blacktulip-virtual.com/lsl-pyoptimizer/online.php](http://lsl.blacktulip-virtual.com/lsl-pyoptimizer/online.php)
- with the default settings 
- and this script: [https://raw.githubusercontent.com/nPoseTeam/nPose-V3/V3.10/nPose%20Scripts/nPose%20Dialog.lsl](https://raw.githubusercontent.com/nPoseTeam/nPose-V3/V3.10/nPose%20Scripts/nPose%20Dialog.lsl)

and got the optimizer output:
```
Traceback (most recent call last):
  File "/home/sei/lslopt_master/main.py", line 742, in <module>
    ret = main(sys.argv)
  File "/home/sei/lslopt_master/main.py", line 738, in main
    werr(e.__class__.__name__ + ': ' + str(e) + '\n')
  File "/home/sei/lslopt_master/strutil.py", line 85, in werr
    sys.stderr.write(any2u(s, sys.stderr))
  File "/usr/lib/python2.7/encodings/__init__.py", line 100, in search_function
    level=0)
MemoryError
```
Is the script too large for the online version?

**Comment by Sei-Lisa** [comment]
It seems so. For security reasons, the online version is given limited memory; however, apparently this limit became too low after a recent system update. I have raised the limits to more reasonable levels.

Thanks for the report!
